{% set name = "eo-learn" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 25e881a4a29d72ab44fec782da0d0e9e5311c82dcf67909e95f4cd822f49c741

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - eo-learn-core
    - eo-learn-coregistration
    - eo-learn-features
    - eo-learn-geometry
    - eo-learn-io
    - eo-learn-mask
    - eo-learn-ml-tools
    - eo-learn-visualization
    - python >=3.5
    - gdal
    - rasterio
    - shapely
    - fiona
test:
  imports:
    - eolearn
    - eolearn.core
    - eolearn.coregistration
    - eolearn.features
    - eolearn.geometry
    - eolearn.io
    - eolearn.mask
    - eolearn.ml_tools
    - eolearn.visualization
  requires:
    - opencv

about:
  home: https://github.com/sentinel-hub/eo-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Earth observation processing framework for machine learning in Python
  doc_url: https://eo-learn.readthedocs.io/en/latest/
  dev_url: https://github.com/sentinel-hub/eo-learn

extra:
  recipe-maintainers:
    - mxr-conda
